travis:
  secure:
    BINSTAR_TOKEN: u60rOZE5z+Pmtr5GYHb7Su8qVwx66y+0sJUjVyEqiLYiu/cohqjscx8x8kK1+GzECbiiLgkC1758Yg/ACgvxPElY+QzrojyLxGmih3ymzpZ1e8uKbxeBrks+yzcqx0gwWfi0CIi0j2/grToKtqgNc5VmjxjROwlzgFLMVG7jS+hXjUIb1ABq+1foglaV1GfIwBG8DHYhylXCOKMwHr8yg77fgVF/05ib63+5Rkfwr6crcWck/+a6jPEfsHfuto+o0elKVM+BDJBEr8M5vrEEJkwuf7K5aOaKLQcoepAzjit8f25lIUZ62BPtTniNztx4/QIFzduFT9iivva0M8OciLUBBk0OYC+zX+PQTjfzoA8Y/G0fLkWvwaQP6iwD/dx/dR/nibfp1qj7FRTQH2v1Y0WFz5sbJe12/AoeV/W8adI7FnDlKpZc5dCc4jOxrZ8w/oTd8Uex6jq/l+k44mn6Ndq/BzXJWVhIp8uwg0JmFE6Nrb7bKnXGOIdQdA2efGHjLC7EQvMfzut81TlfO+686wpRFOx8R5V4mgh20+KchjdfI03XZhMaULWYSQ2IEcCQbEhCk5272jUkANwJiytweUdSFyrHIkqegWJv/pCZNkQZ9AQDZNZ2JVop2bS3dOlGZP8nZjHQWIyXNz/JiLTtRALzIfYMjNNUdg5/kryD9uw=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
